#!/usr/bin/env python3
"""Compute daily order totals for staff-allocation comparison.

Rules based on user definition:
- Jan 1 total: sum of average_orders_per_hour (from first-chart output)
- Jan 2..Jan 31 total: Create Time within [previous day 09:00:00, current day 08:59:59]
  implemented as [start, end) where end is current day 09:00:00.
"""

from __future__ import annotations

import argparse
import csv
from collections import defaultdict
from datetime import date, datetime, time, timedelta
from pathlib import Path


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Daily totals with 09:00-08:59 operation-day windows")
    p.add_argument(
        "--input-csv",
        default="/Users/robinhu/Desktop/Robin/Simulated_Case_Study.csv",
        help="Raw CSV path",
    )
    p.add_argument(
        "--hourly-avg-csv",
        default="data/processed/jan_hourly_average_orders.csv",
        help="Hourly-average CSV generated by first script",
    )
    p.add_argument(
        "--output-daily-csv",
        default="data/processed/daily_orders_for_staff_allocation.csv",
        help="Output per-day totals",
    )
    p.add_argument(
        "--output-summary-csv",
        default="data/processed/staff_allocation_demand_summary.csv",
        help="Output summary metrics",
    )
    p.add_argument(
        "--year",
        type=int,
        default=2026,
        help="Target year",
    )
    p.add_argument(
        "--month",
        type=int,
        default=1,
        help="Target month",
    )
    p.add_argument(
        "--datetime-format",
        default="%Y-%m-%d %H:%M",
        help="Create Time format",
    )
    return p.parse_args()


def month_day_range(year: int, month: int) -> tuple[date, date]:
    first = date(year, month, 1)
    if month == 12:
        next_month = date(year + 1, 1, 1)
    else:
        next_month = date(year, month + 1, 1)
    last = next_month - timedelta(days=1)
    return first, last


def sum_hourly_average(path: Path) -> float:
    if not path.exists():
        return -1.0
    total = 0.0
    with path.open("r", encoding="utf-8", newline="") as f:
        r = csv.DictReader(f)
        if "average_orders_per_hour" not in (r.fieldnames or []):
            return -1.0
        for row in r:
            total += float(row["average_orders_per_hour"])
    return total


def load_create_times(raw_csv: Path, dt_fmt: str) -> list[datetime]:
    if not raw_csv.exists():
        raise FileNotFoundError(f"Input CSV not found: {raw_csv}")

    out: list[datetime] = []
    with raw_csv.open("r", encoding="utf-8-sig", newline="") as f:
        r = csv.DictReader(f)
        if "Create Time" not in (r.fieldnames or []):
            raise KeyError("Column 'Create Time' not found")
        for row in r:
            txt = (row.get("Create Time") or "").strip()
            if not txt:
                continue
            try:
                out.append(datetime.strptime(txt, dt_fmt))
            except ValueError:
                continue
    return out


def main() -> None:
    args = parse_args()

    raw_path = Path(args.input_csv)
    hourly_avg_path = Path(args.hourly_avg_csv)
    output_daily = Path(args.output_daily_csv)
    output_summary = Path(args.output_summary_csv)

    month_start, month_end = month_day_range(args.year, args.month)
    day_count = (month_end - month_start).days + 1

    create_times = load_create_times(raw_path, args.datetime_format)

    # Build counts for operational day labels (target day):
    # if create time >=09:00 => belongs to next day label
    # else belongs to same day label
    op_day_counts: defaultdict[date, int] = defaultdict(int)
    for dt in create_times:
        if dt.date() < month_start or dt.date() > month_end:
            continue
        if dt.time() >= time(9, 0, 0):
            target_day = dt.date() + timedelta(days=1)
        else:
            target_day = dt.date()
        if month_start <= target_day <= month_end:
            op_day_counts[target_day] += 1

    # Jan 1: use sum of average hourly orders from chart-1 output.
    jan1_value = sum_hourly_average(hourly_avg_path)
    jan1_source = "hourly_average_sum"

    if jan1_value < 0:
        # fallback if hourly avg file not found
        jan_total = sum(1 for dt in create_times if month_start <= dt.date() <= month_end)
        jan1_value = jan_total / day_count
        jan1_source = "monthly_total_divided_by_days_fallback"

    rows: list[dict[str, str | int | float]] = []

    # Day 1 row
    rows.append(
        {
            "day": month_start.isoformat(),
            "window_start": f"{month_start.isoformat()} 00:00:00 (special rule)",
            "window_end": f"{month_start.isoformat()} 23:59:59 (special rule)",
            "orders_total": round(jan1_value, 4),
            "source": jan1_source,
        }
    )

    # Day 2..last day rows based on 09:00->08:59 windows
    for d in range(2, day_count + 1):
        current_day = month_start + timedelta(days=d - 1)
        prev_day = current_day - timedelta(days=1)
        start_dt = datetime.combine(prev_day, time(9, 0, 0))
        end_dt = datetime.combine(current_day, time(8, 59, 59))

        rows.append(
            {
                "day": current_day.isoformat(),
                "window_start": start_dt.strftime("%Y-%m-%d %H:%M:%S"),
                "window_end": end_dt.strftime("%Y-%m-%d %H:%M:%S"),
                "orders_total": op_day_counts.get(current_day, 0),
                "source": "create_time_window_prev_09_to_curr_08_59_59",
            }
        )

    # Average of all 31 day totals based on the above definition
    avg_daily = sum(float(r["orders_total"]) for r in rows) / day_count

    output_daily.parent.mkdir(parents=True, exist_ok=True)

    with output_daily.open("w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(
            f,
            fieldnames=["day", "window_start", "window_end", "orders_total", "source"],
        )
        w.writeheader()
        w.writerows(rows)

    with output_summary.open("w", encoding="utf-8", newline="") as f:
        w = csv.writer(f)
        w.writerow(["metric", "value"])
        w.writerow(["month", f"{args.year:04d}-{args.month:02d}"])
        w.writerow(["days_counted", day_count])
        w.writerow(["day1_orders_total_special_rule", f"{jan1_value:.4f}"])
        w.writerow(["days2_to_end_total_orders", int(sum(op_day_counts.get(month_start + timedelta(days=d - 1), 0) for d in range(2, day_count + 1)))])
        w.writerow(["average_daily_orders_defined_method", f"{avg_daily:.4f}"])

    peak_day = max(rows, key=lambda r: float(r["orders_total"]))

    print("=== Daily Orders Calculation Completed ===")
    print(f"Input CSV: {raw_path}")
    print(f"Month: {args.year:04d}-{args.month:02d}")
    print(f"Output daily CSV: {output_daily}")
    print(f"Output summary CSV: {output_summary}")
    print(f"Day-1 total (special rule): {jan1_value:.4f}")
    print(f"Average daily orders (31-day defined method): {avg_daily:.4f}")
    print(f"Peak day by this method: {peak_day['day']} ({peak_day['orders_total']} orders)")


if __name__ == "__main__":
    main()
