#!/usr/bin/env python3
"""Compare staff-allocation efficiency using daily demand from Jan 2-31.

Rules implemented from user request:
- Operational day label uses Create Time windows:
  day D (D>=2) includes records from D-1 09:00:00 to D 08:59:59.
- Total volume = length * width * height parsed from `Product Size (cm) L * W * H`.
- Per-order processing seconds are randomly generated by volume bucket.
- Model A: 4 workers, 10h/day, with fatigue discount after 6h
  (remaining 4h require 1.3-1.4x time => effective output reduced).
- Model B: 6 workers, 6-7h/day.
- Backlog threshold:
  - Model A: orders above 2000/day roll to next day backlog.
  - Model B: orders above 3500/day roll to next day backlog.
"""

from __future__ import annotations

import argparse
import csv
import random
import re
from collections import defaultdict
from dataclasses import dataclass
from datetime import date, datetime, time, timedelta
from pathlib import Path
from statistics import mean, pstdev
from typing import Dict, List, Tuple


SIZE_COL = "Product Size (cm) L * W * H"
CREATE_COL = "Create Time"


@dataclass
class DayResult:
    day: str
    workers: int
    shift_hours: float
    fatigue_factor: float
    backlog_start_orders: int
    incoming_orders: int
    total_demand_orders: int
    threshold_orders: int
    processed_orders: int
    backlog_end_orders: int
    capacity_seconds: float
    processed_seconds: float
    utilization: float
    orders_per_person_hour: float
    daily_labor_cost: float


@dataclass
class ModelSummary:
    model: str
    workers: int
    avg_shift_hours: float
    avg_orders_per_person_hour: float
    avg_daily_processed_orders: float
    std_daily_processed_orders: float
    avg_backlog_end_orders: float
    max_backlog_end_orders: int
    days_with_backlog: int
    total_processed_orders: int
    final_backlog_orders: int
    total_labor_cost: float
    avg_daily_labor_cost: float
    labor_cost_per_processed_order: float


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Staff allocation efficiency comparison")
    p.add_argument(
        "--input-csv",
        default="/Users/robinhu/Desktop/Robin/Simulated_Case_Study.csv",
        help="Raw CSV path",
    )
    p.add_argument(
        "--year",
        type=int,
        default=2026,
        help="Target year",
    )
    p.add_argument(
        "--month",
        type=int,
        default=1,
        help="Target month",
    )
    p.add_argument(
        "--output-daily-csv",
        default="data/processed/staff_allocation_daily_comparison.csv",
        help="Output daily comparison table",
    )
    p.add_argument(
        "--output-summary-csv",
        default="data/processed/staff_allocation_efficiency_summary.csv",
        help="Output summary table",
    )
    p.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed for reproducibility",
    )
    p.add_argument(
        "--hourly-wage",
        type=float,
        default=18.0,
        help="Labor cost per person-hour (default: 18)",
    )
    return p.parse_args()


def month_days(year: int, month: int) -> Tuple[date, date]:
    first = date(year, month, 1)
    if month == 12:
        nxt = date(year + 1, 1, 1)
    else:
        nxt = date(year, month + 1, 1)
    return first, nxt - timedelta(days=1)


def parse_size_volume(size_text: str) -> float:
    # Extract first 3 numeric values from strings like "27.000\r\n14.000\r\n13.000\r\n"
    nums = re.findall(r"\d+(?:\.\d+)?", size_text or "")
    if len(nums) < 3:
        return 0.0
    l, w, h = float(nums[0]), float(nums[1]), float(nums[2])
    return l * w * h


def seconds_by_volume(volume: float, rng: random.Random) -> float:
    # User-defined ranges + one explicit bridging assumption for 1000-2000.
    if volume <= 250:
        return rng.uniform(8, 14)
    if volume <= 500:
        return rng.uniform(10, 15)
    if volume <= 1000:
        return rng.uniform(12, 16)
    if volume <= 2000:
        return rng.uniform(13, 18)  # assumption for uncovered interval
    return rng.uniform(15, 20)


def op_day_label(dt: datetime) -> date:
    # Records created >=09:00 belong to next operation day label.
    if dt.time() >= time(9, 0, 0):
        return dt.date() + timedelta(days=1)
    return dt.date()


def load_orders_by_op_day(
    input_csv: Path,
    year: int,
    month: int,
    rng: random.Random,
) -> Dict[date, List[float]]:
    month_start, month_end = month_days(year, month)

    # We only model operation days from day 2 to day 31 (inclusive)
    op_start = month_start + timedelta(days=1)
    op_end = month_end

    orders: Dict[date, List[float]] = defaultdict(list)

    with input_csv.open("r", encoding="utf-8-sig", newline="") as f:
        r = csv.DictReader(f)
        missing_cols = [c for c in (CREATE_COL, SIZE_COL) if c not in (r.fieldnames or [])]
        if missing_cols:
            raise KeyError(f"Missing required columns: {missing_cols}")

        for row in r:
            ct = (row.get(CREATE_COL) or "").strip()
            if not ct:
                continue
            try:
                dt = datetime.strptime(ct, "%Y-%m-%d %H:%M")
            except ValueError:
                continue

            label = op_day_label(dt)
            if label < op_start or label > op_end:
                continue

            vol = parse_size_volume((row.get(SIZE_COL) or "").strip())
            sec = seconds_by_volume(vol, rng)
            orders[label].append(sec)

    # Ensure each op day exists even if empty.
    d = op_start
    while d <= op_end:
        orders.setdefault(d, [])
        d += timedelta(days=1)

    return dict(sorted(orders.items(), key=lambda kv: kv[0]))


def simulate_model(
    model_name: str,
    orders_by_day: Dict[date, List[float]],
    workers: int,
    threshold: int,
    rng: random.Random,
    fixed_shift_hours: float | None = None,
    shift_range: Tuple[float, float] | None = None,
    fatigue_after_6h: bool = False,
    hourly_wage: float = 18.0,
) -> Tuple[List[DayResult], ModelSummary]:
    backlog: List[float] = []
    day_results: List[DayResult] = []

    for day, incoming in orders_by_day.items():
        demand = backlog + incoming
        backlog_start = len(backlog)

        # Threshold-based forced backlog
        if len(demand) > threshold:
            to_attempt = demand[:threshold]
            forced_backlog = demand[threshold:]
        else:
            to_attempt = demand
            forced_backlog = []

        if fixed_shift_hours is not None:
            shift_hours = fixed_shift_hours
        elif shift_range is not None:
            shift_hours = rng.uniform(shift_range[0], shift_range[1])
        else:
            raise ValueError("Either fixed_shift_hours or shift_range must be provided")

        fatigue_factor = 1.0
        if fatigue_after_6h and shift_hours > 6:
            fatigue_factor = rng.uniform(1.3, 1.4)
            effective_seconds_per_worker = 6 * 3600 + (shift_hours - 6) * 3600 / fatigue_factor
        else:
            effective_seconds_per_worker = shift_hours * 3600

        capacity_seconds = workers * effective_seconds_per_worker

        processed_orders = 0
        processed_seconds = 0.0
        for sec in to_attempt:
            if processed_seconds + sec <= capacity_seconds:
                processed_seconds += sec
                processed_orders += 1
            else:
                break

        unprocessed = to_attempt[processed_orders:]
        backlog = forced_backlog + unprocessed

        utilization = processed_seconds / capacity_seconds if capacity_seconds > 0 else 0.0
        orders_per_person_hour = processed_orders / (workers * shift_hours)
        daily_labor_cost = workers * shift_hours * hourly_wage

        day_results.append(
            DayResult(
                day=day.isoformat(),
                workers=workers,
                shift_hours=round(shift_hours, 4),
                fatigue_factor=round(fatigue_factor, 4),
                backlog_start_orders=backlog_start,
                incoming_orders=len(incoming),
                total_demand_orders=len(demand),
                threshold_orders=threshold,
                processed_orders=processed_orders,
                backlog_end_orders=len(backlog),
                capacity_seconds=round(capacity_seconds, 2),
                processed_seconds=round(processed_seconds, 2),
                utilization=round(utilization, 4),
                orders_per_person_hour=round(orders_per_person_hour, 4),
                daily_labor_cost=round(daily_labor_cost, 4),
            )
        )

    processed_series = [r.processed_orders for r in day_results]
    backlog_series = [r.backlog_end_orders for r in day_results]
    oph_series = [r.orders_per_person_hour for r in day_results]
    shift_series = [r.shift_hours for r in day_results]
    daily_cost_series = [r.daily_labor_cost for r in day_results]

    total_processed = sum(processed_series)
    total_labor_cost = sum(daily_cost_series)
    labor_cost_per_order = (total_labor_cost / total_processed) if total_processed > 0 else 0.0

    summary = ModelSummary(
        model=model_name,
        workers=workers,
        avg_shift_hours=round(mean(shift_series), 4),
        avg_orders_per_person_hour=round(mean(oph_series), 4),
        avg_daily_processed_orders=round(mean(processed_series), 4),
        std_daily_processed_orders=round(pstdev(processed_series), 4),
        avg_backlog_end_orders=round(mean(backlog_series), 4),
        max_backlog_end_orders=max(backlog_series) if backlog_series else 0,
        days_with_backlog=sum(1 for x in backlog_series if x > 0),
        total_processed_orders=total_processed,
        final_backlog_orders=backlog_series[-1] if backlog_series else 0,
        total_labor_cost=round(total_labor_cost, 4),
        avg_daily_labor_cost=round(mean(daily_cost_series), 4),
        labor_cost_per_processed_order=round(labor_cost_per_order, 4),
    )

    return day_results, summary


def write_daily_csv(path: Path, rows: List[DayResult], model_name: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    write_header = not path.exists()

    with path.open("a", encoding="utf-8", newline="") as f:
        w = csv.writer(f)
        if write_header:
            w.writerow(
                [
                    "model",
                    "day",
                    "workers",
                    "shift_hours",
                    "fatigue_factor",
                    "backlog_start_orders",
                    "incoming_orders",
                    "total_demand_orders",
                    "threshold_orders",
                    "processed_orders",
                    "backlog_end_orders",
                    "capacity_seconds",
                    "processed_seconds",
                    "utilization",
                    "orders_per_person_hour",
                    "daily_labor_cost",
                ]
            )

        for r in rows:
            w.writerow(
                [
                    model_name,
                    r.day,
                    r.workers,
                    r.shift_hours,
                    r.fatigue_factor,
                    r.backlog_start_orders,
                    r.incoming_orders,
                    r.total_demand_orders,
                    r.threshold_orders,
                    r.processed_orders,
                    r.backlog_end_orders,
                    r.capacity_seconds,
                    r.processed_seconds,
                    r.utilization,
                    r.orders_per_person_hour,
                    r.daily_labor_cost,
                ]
            )


def write_summary_csv(path: Path, summaries: List[ModelSummary]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as f:
        w = csv.writer(f)
        w.writerow(
            [
                "model",
                "workers",
                "avg_shift_hours",
                "avg_orders_per_person_hour",
                "avg_daily_processed_orders",
                "std_daily_processed_orders",
                "avg_backlog_end_orders",
                "max_backlog_end_orders",
                "days_with_backlog",
                "total_processed_orders",
                "final_backlog_orders",
                "total_labor_cost",
                "avg_daily_labor_cost",
                "labor_cost_per_processed_order",
            ]
        )
        for s in summaries:
            w.writerow(
                [
                    s.model,
                    s.workers,
                    s.avg_shift_hours,
                    s.avg_orders_per_person_hour,
                    s.avg_daily_processed_orders,
                    s.std_daily_processed_orders,
                    s.avg_backlog_end_orders,
                    s.max_backlog_end_orders,
                    s.days_with_backlog,
                    s.total_processed_orders,
                    s.final_backlog_orders,
                    s.total_labor_cost,
                    s.avg_daily_labor_cost,
                    s.labor_cost_per_processed_order,
                ]
            )


def main() -> None:
    args = parse_args()

    input_csv = Path(args.input_csv)
    output_daily = Path(args.output_daily_csv)
    output_summary = Path(args.output_summary_csv)

    if not input_csv.exists():
        raise FileNotFoundError(f"Input CSV not found: {input_csv}")

    # Clear daily file each run so it is reproducible.
    if output_daily.exists():
        output_daily.unlink()

    rng_data = random.Random(args.seed)
    orders_by_day = load_orders_by_op_day(input_csv, args.year, args.month, rng_data)

    # Separate RNG streams for model behavior reproducibility
    rng_m4 = random.Random(args.seed + 100)
    rng_m6 = random.Random(args.seed + 200)

    m4_days, m4_summary = simulate_model(
        model_name="4_workers_10h",
        orders_by_day=orders_by_day,
        workers=4,
        threshold=2000,
        rng=rng_m4,
        fixed_shift_hours=10.0,
        fatigue_after_6h=True,
        hourly_wage=args.hourly_wage,
    )

    m6_days, m6_summary = simulate_model(
        model_name="6_workers_6to7h",
        orders_by_day=orders_by_day,
        workers=6,
        threshold=3500,
        rng=rng_m6,
        shift_range=(6.0, 7.0),
        fatigue_after_6h=False,
        hourly_wage=args.hourly_wage,
    )

    write_daily_csv(output_daily, m4_days, "4_workers_10h")
    write_daily_csv(output_daily, m6_days, "6_workers_6to7h")
    write_summary_csv(output_summary, [m4_summary, m6_summary])

    print("=== Staff Allocation Efficiency Comparison Completed ===")
    print(f"Input CSV: {input_csv}")
    print(f"Daily output: {output_daily}")
    print(f"Summary output: {output_summary}")
    print("Assumption used: volume 1000-2000 => random 13-18 sec/order")
    print(f"Hourly wage used: ${args.hourly_wage:.2f} per person-hour")
    print()
    print(
        f"Model 4_workers_10h avg orders/person/hour: {m4_summary.avg_orders_per_person_hour:.4f}"
    )
    print(
        f"Model 6_workers_6to7h avg orders/person/hour: {m6_summary.avg_orders_per_person_hour:.4f}"
    )
    print(
        f"Model 4_workers_10h total labor cost: ${m4_summary.total_labor_cost:.2f} "
        f"(avg/day ${m4_summary.avg_daily_labor_cost:.2f})"
    )
    print(
        f"Model 6_workers_6to7h total labor cost: ${m6_summary.total_labor_cost:.2f} "
        f"(avg/day ${m6_summary.avg_daily_labor_cost:.2f})"
    )
    print(
        f"Model 4_workers_10h labor cost/order: ${m4_summary.labor_cost_per_processed_order:.4f}"
    )
    print(
        f"Model 6_workers_6to7h labor cost/order: ${m6_summary.labor_cost_per_processed_order:.4f}"
    )

    if m6_summary.avg_orders_per_person_hour > m4_summary.avg_orders_per_person_hour:
        print("Result: 6-worker model shows higher average per-person hourly efficiency.")
    elif m6_summary.avg_orders_per_person_hour < m4_summary.avg_orders_per_person_hour:
        print("Result: 4-worker model shows higher average per-person hourly efficiency.")
    else:
        print("Result: both models are equal on average per-person hourly efficiency.")


if __name__ == "__main__":
    main()
